# Generated by Django 5.1.3 on 2024-12-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_orderitem_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"verbose_name_plural": "Manufacturer"},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="password",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
    ]
