# Generated by Django 5.1.3 on 2024-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_alter_category_options_alter_manufacturer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("assistant_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
